# Este programa deve ler uma tabela em csv e gerar imagens QR Code das mesmas.
# O arquivo de entrada de se chamar bits.csv e deve conter uma coluna 'Etiqueta' e outra 'Imagem',
# sendo que a coluna 'etiqueta' deve conter o texto com o nome do arquivo a ser gerado para a 
# etiqueta. As colunas devem ter títulos.
# A coluna 'Imagem' deve conter o link http para a imagem do bit na internet. 


module GeraEtiqueta
  #
  
  def gera_tabela(file)
    require 'csv'
    table = CSV.parse(File.read(file), headers: true, col_sep: ",")
    return table
  end
  
  def mostra_tabela(tabela)
    #
    puts "Olhaí a tabela..."
    puts
    puts tabela
    puts
  
    puts
    puts "Surprise MTF! I'm in a method now!"
    puts
  end
  
  def mostra_linha(tabela)
    #
    # Agora linha a linha
    puts "Agora linha  a linha:"
    tabela.each { |line| puts line }
    puts
    puts "BTW this is generated by a method!"
    puts
  end
  
  
  def mostra_etiqueta(tabela)
    #
    # Agora só as etiquetas
    puts
    puts "Agora só as etiquetas"
    tabela.each { |line| puts line["Etiqueta"] }
    puts
    puts "Aaaaaand we're on a method..."
    puts
    puts
  end
  
  def mostra_imagem(tabela)
    #
    # Agora só os links para as imagens
    puts "Agora só os links para as imagens"
    tabela.each { |line| puts line["Imagem"] }
    puts
    puts "mostrando os links via método..."
    puts
  end
  
  def cria_qr(file, bit)
    #
    require 'barby'                           # => true
    require 'barby/barcode/qr_code'           # => true
    require 'barby/outputter/png_outputter'   # => true
    # bit = 'https://www.eliane.com/upload/produtos/eliane-fossile-po-90x90cm-01-260x260.jpg'
    # file = '3. Fossile'
    blob = Barby::QrCode.new(bit, level: :q, size: 10).to_png
    File.open("#{file}.png", 'wb'){|f| f.write blob}
    puts "O QR Code do #{file} foi criado!"  
  end
  
  
  def cria_etiqueta(tabela)
    puts "Vamos criar as etiquetas."
    tabela.each do |line| 
      file = line["Etiqueta"]
      bit =  line["Imagem"]
      puts "Criando QRCode para #{file} on link #{bit}"
      cria_qr(file, bit)
    end
  end
end


include GeraEtiqueta
puts "O módulo GeraEtiqueta foi incluído com sucesso!"

arquivo_de_entrada = 'bits.csv'
puts "O arquivo de entrada foi reconhecido com sucesso."

tabela = gera_tabela(arquivo_de_entrada)
puts "A tabela foi criada."

cria_etiqueta(tabela)
puts "As etiquetas foram criadas..."


# mostra_tabela(tabela)
# mostra_linha(tabela)
# mostra_etiqueta(tabela)
# mostra_imagem(tabela)









